const H=window.MCL_HUBS;
const META=window.MCL_MISSION_META||{};
const LINKS=window.MCL_LINKS||{};
const HUBLINKS=window.MCL_HUB_LINKS||{};
const T=H.flatMap(h=>h[6].map(t=>({n:t[0],d:t[1],e:t[2],h:h[0]})));
const TB=Object.fromEntries(T.map(t=>[t.n,t]));
const HB=Object.fromEntries(H.map(h=>[h[0],h]));
let S={r:'home',h:null,t:null,map:null,pin:false,q:{}};
const A=document.getElementById('app'),tip=document.getElementById('tip'),cnt=document.getElementById('cnt'),search=document.getElementById('search'),res=document.getElementById('res'),tt=document.getElementById('tt'),td=document.getElementById('td'),te=document.getElementById('te'),openTerm=document.getElementById('openTerm'),pinTip=document.getElementById('pinTip'),closeTip=document.getElementById('closeTip');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const reEsc=s=>s.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');
const conceptNames=T.map(x=>x.n).sort((a,b)=>b.length-a.length);
const conceptRE=new RegExp('\\b('+conceptNames.map(reEsc).join('|')+')\\b','gi');
function linkText(s,current=''){let out='',last=0;String(s).replace(conceptRE,(m,_g,off)=>{out+=esc(String(s).slice(last,off));out+=m.toLowerCase()===String(current).toLowerCase()?esc(m):`<button class="inlineTerm" data-tip="${esc(TB[m]?.n||m)}">${esc(m)}</button>`;last=off+m.length;return m});return out+esc(String(s).slice(last))}
const book=()=>JSON.parse(localStorage.mclbook||'[]');
const saveBook=b=>{localStorage.mclbook=JSON.stringify(b);count()};
const prof=()=>JSON.parse(localStorage.mclprof||'{}');
const scores=()=>JSON.parse(localStorage.mclscores||'{}');
const uniqueMissions=()=>{let m=new Map();book().forEach(x=>m.set(x.h+'|'+x.l,x));return [...m.values()]};
function count(){cnt.textContent=uniqueMissions().length}
function toast(x){let n=document.createElement('div');n.className='toast';n.textContent=x;document.body.append(n);setTimeout(()=>n.remove(),1900)}
function comp(id){let b=uniqueMissions(),a=b.some(x=>x.h===id&&x.l==='m'),z=b.some(x=>x.h===id&&x.l==='h');return(a?50:0)+(z?50:0)}
function xp(){let total=0;uniqueMissions().forEach(x=>total+=(META[x.h]?.[x.l]?.xp||0));Object.values(scores()).forEach(v=>total+=(Math.min(v,5)*20));return total}
function totalXP(){let missions=H.reduce((s,h)=>s+(META[h[0]]?.micro?.xp||100)+(META[h[0]]?.hub?.xp||250),0);return missions+H.length*100}
function go(r,o={}){S.r=r;Object.assign(S,o);document.querySelectorAll('[data-go]').forEach(b=>b.classList.toggle('on',b.dataset.go===r));tip.classList.remove('show');render();scrollTo({top:0,behavior:'smooth'})}
function render(){count();if(S.r==='home')home();if(S.r==='hub')hub(S.h);if(S.r==='term')term(S.t);if(S.r==='map')map();if(S.r==='missions')missions();if(S.r==='book')playbook();bind()}
function home(){let done=H.filter(h=>comp(h[0])===100).length;A.innerHTML=`
<section class="card hero"><div class="ey">Knowledge + Challenge System</div><h2>LEARN IT.<br>USE IT.</h2><p>One connected marketing encyclopedia now powers <b>${T.length}</b> searchable concepts. Hover or tap any linked term for a fast definition, open the full entry for depth, then prove it in decision-based missions.</p><div class="stats"><div class="st"><b>${H.length}</b><small>Concept hubs</small></div><div class="st"><b>${T.length}</b><small>Searchable entries</small></div><div class="st"><b>${H.length*2}</b><small>Challenge missions</small></div><div class="st"><b>${xp()}</b><small>XP earned</small></div></div><div class="xpbar"><span style="width:${Math.min(100,Math.round(xp()/totalXP()*100))}%"></span></div><small class="muted">${done}/${H.length} hubs mastered · ${totalXP()} total XP available</small></section>
<section class="sectiontitle"><div><div class="ey">Encyclopedia Architecture</div><h2>Concept Hubs</h2></div><p>${T.length} concepts organized so students can go from big idea → subtype → metric → strategy.</p></section>
<section class="grid">${H.map((h,i)=>`<button class="hub" data-hub="${h[0]}"><div class="ey">Hub ${i+1} · ${h[6].length} concepts</div><h3>${h[1]}</h3><p>${h[2]}</p><div class="barline"><span style="width:${comp(h[0])}%"></span></div><small>${comp(h[0])}% mission mastery</small></button>`).join('')}</section>`}
function relatedTermNames(n){let t=TB[n];if(!t)return[];let explicit=LINKS[n]||[];let siblings=HB[t.h][6].map(x=>x[0]).filter(x=>x!==n);let text=(t.d+' '+t.e).toLowerCase();let mentioned=T.filter(x=>x.n!==n&&text.includes(x.n.toLowerCase())).map(x=>x.n);return [...new Set([...explicit,...mentioned,...siblings])].filter(x=>TB[x]).slice(0,12)}
function hub(id){let h=HB[id],sc=scores()[id]||0,meta=META[id]||{};S.h=id;A.innerHTML=`
<div class="crumb"><button data-go="home">Marketing Library</button> &gt; <b>${h[1]}</b></div><div class="two"><div>
<section class="card hero"><div class="ey">Concept Hub · ${h[6].length} entries</div><h2>${h[1].toUpperCase()}</h2><p>${linkText(h[2])}</p><div class="actions"><button class="btn primary" data-scroll="concepts">Explore concepts</button><button class="btn" data-scroll="ms">Enter mission zone</button><button class="btn" data-map="${id}">Map connections</button></div></section>
<section id="concepts" class="card"><div class="ey">Drill Down</div><h2>${h[6].length} Concepts</h2><p class="muted">Hover a concept for the instant definition. Click it for the full encyclopedia entry.</p><div class="grid termgrid">${h[6].map(t=>`<button class="term" data-termopen="${esc(t[0])}" data-hoverterm="${esc(t[0])}"><b>${t[0]}</b><small>${t[1]}</small></button>`).join('')}</div></section>
<section class="card"><div class="ey">Quick Check · Best ${sc}/5</div><h2>Concept Match</h2><p class="muted">Five fast checks. Each correct answer contributes to your hub XP.</p><div id="quiz">${quiz(h)}</div></section>
<div id="ms">${mission(h,'m')}</div>${mission(h,'h')}</div>
<aside><div class="call"><b>Common Mistake</b><p>${h[3]}</p></div><section class="card"><div class="ey">Cross-Hub Connections</div><div class="chips">${(HUBLINKS[id]||[]).map(x=>`<button class="chip" data-hub="${x}">${HB[x][1]}</button>`).join('')}</div></section><section class="card"><div class="ey">Mission Progress</div><h2>${comp(id)}%</h2><div class="barline"><span style="width:${comp(id)}%"></span></div><p class="muted">${meta.role?'Role: '+meta.role:''}</p></section></aside></div>`}
function quiz(h){let chosen=S.q[h[0]]||{},base=h[6].slice(0,5);return base.map((t,i)=>{let pool=[t[0],h[6][(i+4)%h[6].length][0],h[6][(i+8)%h[6].length][0],h[6][(i+12)%h[6].length][0]];let opts=[...new Set(pool)].sort((a,b)=>a.localeCompare(b));return`<div class="quizrow"><p><b>${i+1}.</b> ${t[1]}</p>${opts.map(o=>`<button class="opt ${chosen[i]===o?'sel':''}" data-q="${h[0]}|${i}|${esc(o)}">${o}</button>`).join('')}</div>`}).join('')+`<button class="btn primary" data-check="${h[0]}">Check answers</button>`}
function draftKey(id,l){return`mcldraftv3-${id}-${l}`}
function twistKey(id,l){return`mcltwist-${id}-${l}`}
function getDraft(id,l){try{return JSON.parse(localStorage[draftKey(id,l)]||'[]')}catch{return[]}}
function mission(h,l){let core=l==='m'?h[4]:h[5],meta=META[h[0]]?.[l==='m'?'micro':'hub']||{time:l==='m'?8:20,xp:l==='m'?100:250,steps:[core[1]],twists:[]},saved=uniqueMissions().some(x=>x.h===h[0]&&x.l===l),draft=getDraft(h[0],l),twist=localStorage[twistKey(h[0],l)]||'',level=l==='m'?'FIELD DRILL':'BOSS MISSION';return`
<section class="mission gameMission" id="mission-${h[0]}-${l}"><div class="missionTop"><div><div class="ey">${level} · ${meta.xp} XP</div><h3>${core[0]}</h3></div><div class="missionBadge">${meta.time} MIN</div></div><div class="briefing"><b>Your role: ${META[h[0]]?.role||'Marketing Analyst'}</b><p>${core[1]}</p></div><div class="intel"><div class="ey">Mission Intel</div><div class="chips">${h[6].slice(0,6).map(t=>`<button class="chip" data-tip="${esc(t[0])}">${t[0]}</button>`).join('')}</div></div><div class="twistbox ${twist?'active':''}"><div><div class="ey">Pressure Test</div><b>${twist||'Optional: draw a surprise constraint after you build your first idea.'}</b></div><button class="btn" data-twist="${h[0]}|${l}">${twist?'Redraw Twist':'Draw Twist'}</button></div><div class="decisionGrid">${meta.steps.map((s,i)=>`<label class="decision"><span><b>Decision ${i+1}</b> · ${s}</span><textarea data-mfield="${h[0]}|${l}|${i}" placeholder="Make the decision and explain your business reason...">${esc(draft[i]||'')}</textarea></label>`).join('')}</div><div class="missionFooter"><div class="quality"><b>Quality check:</b> specific decision · business reason · vocabulary · evidence/metric when appropriate</div><button class="btn primary" data-save="${h[0]}|${l}">${saved?'Update Playbook Mission':'Complete Mission + Save'}</button></div></section>`}
function term(n){let t=TB[n];if(!t)return go('home');let h=HB[t.h],rels=relatedTermNames(n),cross=(HUBLINKS[t.h]||[]).map(id=>HB[id]);A.innerHTML=`
<div class="crumb"><button data-go="home">Library</button> &gt; <button data-hub="${t.h}">${h[1]}</button> &gt; <b>${t.n}</b></div><div class="two"><div>
<section class="card hero"><div class="ey">Encyclopedia Entry · ${h[1]}</div><h2>${t.n}</h2><p class="entrydef">${linkText(t.d,t.n)}</p></section>
<section class="example"><b>See it in the wild</b><p>${linkText(t.e,t.n)}</p></section>
<section class="card"><div class="ey">Why it connects</div><h2>Marketing decisions do not live alone.</h2><p>Use the related concepts below to move sideways through the encyclopedia instead of backing all the way out.</p><div class="chips bigchips">${rels.map(x=>`<button class="chip" data-termopen="${esc(x)}" data-hoverterm="${esc(x)}">${x}</button>`).join('')}</div></section>
<section class="card"><div class="ey">60-Second Try It</div><h2>Use ${t.n}</h2><p>Find or invent one business situation where <b>${t.n}</b> matters. State the decision, the business reason, and what result you would measure.</p></section></div>
<aside><section class="card"><div class="ey">Parent Hub</div><button class="btn primary" data-hub="${t.h}">${h[1]}</button></section><section class="card"><div class="ey">Connected Hubs</div><div class="chips">${cross.map(x=>`<button class="chip" data-hub="${x[0]}">${x[1]}</button>`).join('')}</div></section><section class="card stickyGloss"><div class="ey">Definition follows you</div><p>Hover/tap any connected term for its definition. Use <b>Pin</b> to keep that definition visible while you read.</p></section></aside></div>`}
function map(){let h=HB[S.map]||H[0];S.map=h[0];let center=S.t&&TB[S.t]?TB[S.t]:null;let centerName=center?.n||h[1];let related=center?relatedTermNames(center.n):h[6].slice(0,10).map(x=>x[0]);let cross=HUBLINKS[h[0]]||[];A.innerHTML=`
<section class="card hero"><div class="ey">Visual Connections</div><h2>CONCEPT NETWORK</h2><p>Recenter the map on a hub or vocabulary term to see how ideas connect across the system.</p></section>
<div class="chips">${H.map(x=>`<button class="chip" data-map="${x[0]}">${x[1]}</button>`).join('')}</div>
<section class="network"><div class="networkSide"><div class="ey">Connected Hubs</div>${cross.map(id=>`<button class="node hubnode" data-map="${id}">${HB[id][1]}</button>`).join('')}</div><div class="networkCore"><button class="center" ${center?`data-termopen="${esc(center.n)}"`:''}>${centerName}</button><p class="muted">${center?center.d:h[2]}</p></div><div class="networkSide"><div class="ey">Connected Concepts</div>${related.map(n=>`<button class="node" data-mapterm="${esc(n)}">${n}</button>`).join('')}</div></section>`}
function missions(){let b=uniqueMissions();A.innerHTML=`
<section class="card hero"><div class="ey">Application Layer</div><h2>MISSION BOARD</h2><p>Micro missions are short field drills. Hub missions are larger boss challenges. Every mission includes a role, decision checkpoints, vocabulary intel, and an optional pressure-test twist.</p><div class="stats"><div class="st"><b>${b.length}/${H.length*2}</b><small>Missions completed</small></div><div class="st"><b>${xp()}</b><small>XP earned</small></div><div class="st"><b>${H.length}</b><small>Career roles</small></div><div class="st"><b>${H.length*6}</b><small>Possible twists</small></div></div></section>
<section class="grid">${H.flatMap(h=>[['m',h[4]],['h',h[5]]].map(([l,m])=>{let meta=META[h[0]]?.[l==='m'?'micro':'hub'];return`<button class="hub missionCard" data-hubmission="${h[0]}|${l}"><div class="ey">${h[1]} · ${l==='m'?'Field Drill':'Boss Mission'} · ${meta?.xp||0} XP</div><h3>${m[0]}</h3><p>${m[1]}</p><small>${b.some(x=>x.h===h[0]&&x.l===l)?'✓ Complete · replay/update':'Enter challenge →'}</small></button>`})).join('')}</section>`}
function playbook(){let b=book(),u=uniqueMissions(),p=prof(),html=`<section class="card hero"><div class="ey">Student Portfolio</div><h2>MY PLAYBOOK</h2><p>Mission decisions saved on this browser appear here. New missions save the individual decision checkpoints plus any pressure-test twist.</p><div class="stats"><div class="st"><b>${u.length}</b><small>Unique missions</small></div><div class="st"><b>${H.filter(h=>comp(h[0])===100).length}</b><small>Hubs mastered</small></div><div class="st"><b>${Object.keys(scores()).length}</b><small>Quick checks</small></div><div class="st"><b>${xp()}</b><small>XP earned</small></div></div></section>`;html+=`<section class="card"><div class="profile"><input id="pn" class="field" placeholder="Student name" value="${esc(p.n||'')}"><select id="pp" class="field"><option value="">Period</option>${[1,2,3,4,5,6,7].map(x=>`<option ${String(p.p)===String(x)?'selected':''}>${x}</option>`).join('')}</select><button id="ps" class="btn primary">Save Student</button></div><div class="actions"><button id="export" class="btn">Export .txt</button><button id="clearbook" class="btn">Clear Playbook</button></div></section>`;if(!b.length)html+='<div class="card muted">No mission work saved yet.</div>';else b.slice().reverse().forEach(x=>{let body=x.answers?x.answers.map((a,i)=>`<p><b>Decision ${i+1}:</b> ${esc(a).replace(/\n/g,'<br>')}</p>`).join(''):`<p>${esc(x.text||'').replace(/\n/g,'<br>')}</p>`;html+=`<article class="play"><div class="ey">${esc(HB[x.h]?.[1]||x.h)} · ${x.l==='m'?'Field Drill':'Boss Mission'}</div><h3>${esc(x.title)}</h3><small class="muted">${esc(x.date)}${x.student?' · '+esc(x.student):''}${x.period?' · Period '+esc(x.period):''}</small>${x.twist?`<div class="savedTwist"><b>Pressure test:</b> ${esc(x.twist)}</div>`:''}${body}</article>`});A.innerHTML=html}
function bind(){document.querySelectorAll('[data-go]').forEach(x=>x.onclick=()=>go(x.dataset.go));document.querySelectorAll('[data-hub]').forEach(x=>x.onclick=()=>go('hub',{h:x.dataset.hub}));document.querySelectorAll('[data-termopen]').forEach(x=>{x.onclick=()=>go('term',{t:x.dataset.termopen});x.onmouseenter=()=>{if(matchMedia('(hover:hover)').matches)showtip(x.dataset.termopen)}});document.querySelectorAll('[data-hoverterm]').forEach(x=>x.onmouseenter=()=>{if(matchMedia('(hover:hover)').matches)showtip(x.dataset.hoverterm)});document.querySelectorAll('[data-tip]').forEach(x=>{x.onclick=e=>{e.preventDefault();e.stopPropagation();showtip(x.dataset.tip)};x.onmouseenter=()=>{if(matchMedia('(hover:hover)').matches)showtip(x.dataset.tip)}});document.querySelectorAll('[data-scroll]').forEach(x=>x.onclick=()=>document.getElementById(x.dataset.scroll)?.scrollIntoView({behavior:'smooth'}));document.querySelectorAll('[data-map]').forEach(x=>x.onclick=()=>go('map',{map:x.dataset.map,t:null}));document.querySelectorAll('[data-mapterm]').forEach(x=>x.onclick=()=>{S.t=x.dataset.mapterm;S.map=TB[S.t]?.h||S.map;render()});document.querySelectorAll('[data-hubmission]').forEach(x=>x.onclick=()=>{let[id,l]=x.dataset.hubmission.split('|');go('hub',{h:id});setTimeout(()=>document.getElementById(`mission-${id}-${l}`)?.scrollIntoView({behavior:'smooth'}),100)});document.querySelectorAll('[data-q]').forEach(x=>x.onclick=()=>{let[a,b,...rest]=x.dataset.q.split('|');let c=rest.join('|');S.q[a]=S.q[a]||{};S.q[a][b]=c;render()});document.querySelectorAll('[data-check]').forEach(x=>x.onclick=()=>check(x.dataset.check));document.querySelectorAll('[data-save]').forEach(x=>x.onclick=()=>saveMission(...x.dataset.save.split('|')));document.querySelectorAll('[data-twist]').forEach(x=>x.onclick=()=>drawTwist(...x.dataset.twist.split('|')));document.querySelectorAll('[data-mfield]').forEach(x=>x.oninput=()=>saveDraftField(x));if(document.getElementById('ps'))document.getElementById('ps').onclick=()=>{localStorage.mclprof=JSON.stringify({n:document.getElementById('pn').value.trim(),p:document.getElementById('pp').value});toast('Student setup saved')};if(document.getElementById('export'))document.getElementById('export').onclick=exportBook;if(document.getElementById('clearbook'))document.getElementById('clearbook').onclick=()=>{if(confirm('Clear all saved Playbook responses?')){localStorage.removeItem('mclbook');render()}}}
function showtip(n){let t=TB[n];if(!t)return;tt.textContent=n;td.textContent=t.d;te.textContent='Example: '+t.e;openTerm.dataset.n=n;tip.classList.add('show')}
openTerm.onclick=()=>go('term',{t:openTerm.dataset.n});pinTip.onclick=()=>{S.pin=!S.pin;pinTip.textContent=S.pin?'Unpin':'Pin'};closeTip.onclick=()=>{S.pin=false;tip.classList.remove('show')};document.addEventListener('click',e=>{if(!S.pin&&!e.target.closest('.tip')&&!e.target.closest('[data-tip]'))tip.classList.remove('show')});
function check(id){let h=HB[id],chosen=S.q[id]||{},correct=0;h[6].slice(0,5).forEach((t,i)=>{if(chosen[i]===t[0])correct++});let s=scores();s[id]=Math.max(s[id]||0,correct);localStorage.mclscores=JSON.stringify(s);toast(`Quick Check: ${correct}/5 · ${correct*20} XP`);render()}
function saveDraftField(el){let[id,l,i]=el.dataset.mfield.split('|'),arr=getDraft(id,l);arr[+i]=el.value;localStorage[draftKey(id,l)]=JSON.stringify(arr)}
function drawTwist(id,l){let meta=META[id]?.[l==='m'?'micro':'hub'];if(!meta?.twists?.length)return;let old=localStorage[twistKey(id,l)],options=meta.twists.filter(x=>x!==old),pick=options[Math.floor(Math.random()*options.length)]||meta.twists[0];localStorage[twistKey(id,l)]=pick;render();setTimeout(()=>document.getElementById(`mission-${id}-${l}`)?.scrollIntoView({behavior:'smooth',block:'center'}),60);toast('New pressure test drawn')}
function saveMission(id,l){let h=HB[id],core=l==='m'?h[4]:h[5],meta=META[id]?.[l==='m'?'micro':'hub'],answers=getDraft(id,l),steps=meta?.steps||[core[1]];if(answers.length<steps.length||steps.some((_,i)=>!(answers[i]||'').trim()))return toast('Complete every decision checkpoint first');let p=prof(),b=book(),twist=localStorage[twistKey(id,l)]||'';b.push({h:id,l,title:core[0],answers:answers.slice(0,steps.length),twist,date:new Date().toLocaleString(),student:p.n||'',period:p.p||''});saveBook(b);toast(`Mission complete · +${meta?.xp||0} XP`);render();setTimeout(()=>document.getElementById(`mission-${id}-${l}`)?.scrollIntoView({behavior:'smooth'}),50)}
function exportBook(){let b=book(),p=prof(),txt=`MARKETING PLAYBOOK\nStudent: ${p.n||''}\nPeriod: ${p.p||''}\nXP: ${xp()}\n\n`;b.forEach(x=>{txt+=`${HB[x.h]?.[1]||x.h} — ${x.title}\n${x.date}\n`;if(x.twist)txt+=`Pressure Test: ${x.twist}\n`;if(x.answers)x.answers.forEach((a,i)=>txt+=`Decision ${i+1}: ${a}\n`);else txt+=(x.text||'')+'\n';txt+='\n---\n\n'});let blob=new Blob([txt],{type:'text/plain'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`Marketing_Playbook_${(p.n||'Student').replace(/[^a-z0-9]+/gi,'_')}.txt`;a.click();setTimeout(()=>URL.revokeObjectURL(url),500)}
const searchIndex=[...T.map(x=>({n:x.n,d:x.d,h:x.h,type:'term'})),...H.map(x=>({n:x[1],d:x[2],h:x[0],type:'hub'}))];search.oninput=()=>{let q=search.value.trim().toLowerCase();if(!q){res.classList.remove('show');return}let hits=searchIndex.filter(x=>(x.n+' '+x.d).toLowerCase().includes(q)).slice(0,12);res.innerHTML=hits.length?hits.map(x=>`<button class="result" data-result="${x.type}|${esc(x.type==='term'?x.n:x.h)}"><b>${x.n}</b><small>${x.d}</small></button>`).join(''):'<div class="result"><small>No concept found.</small></div>';res.classList.add('show');res.querySelectorAll('[data-result]').forEach(r=>r.onclick=()=>{let[type,...rest]=r.dataset.result.split('|'),v=rest.join('|');search.value='';res.classList.remove('show');type==='term'?go('term',{t:v}):go('hub',{h:v})})};document.addEventListener('click',e=>{if(!res.contains(e.target)&&e.target!==search)res.classList.remove('show')});
document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));count();render();