// Additional cases to increase company and strategy variety.
[
{id:'coke-share',company:'Coca-Cola',title:'Share a Coke returns with personalization for a new generation',summary:'Coca-Cola relaunched Share a Coke with personalized packaging, digital sharing and in-person experiences aimed at creating connection with younger consumers.',url:'https://www.coca-colacompany.com/media-center/iconic-share-a-coke-is-back-for-a-new-generation',hubs:['target','brand','promo','mix'],tags:['Personalization','Packaging','Target Market','Gen Z','Experiential Marketing','Integrated Marketing Communications','Brand Equity','Customer Engagement','Product','Promotion']},
{id:'lego-ideas',company:'LEGO',title:'LEGO Ideas turns fan concepts into a crowdsourced innovation pipeline',summary:'LEGO Ideas gives fans a formal path to submit product concepts, gain community support and potentially become official LEGO products.',url:'https://www.lego.com/en-us/aboutus/news/2019/october/ideas-10th-anniversary',hubs:['fund','ent','brand','mix'],tags:['Crowdsourcing','Co-Creation','Product Development','Market Research','Idea Generation','Innovation','Customer Feedback','Community','Product']},
{id:'shopify-entrepreneurship',company:'Shopify',title:'Shopify studies what is driving a new wave of entrepreneurship',summary:'Shopify combines merchant data and survey research to examine founder motivations, startup capital, growth and barriers to business ownership.',url:'https://www.shopify.com/news/igniting-entrepreneurship',hubs:['ent','fund','strategy'],tags:['Entrepreneur','Opportunity Recognition','Startup Capital','Bootstrapping','Market Research','Growth','Risk','Business Ownership','Primary Research','Secondary Research']},
{id:'dove-real-beauty',company:'Dove',title:'Dove extends Real Beauty into the AI era',summary:'Dove builds on its long-running Real Beauty positioning by committing to authentic representation and addressing AI-generated beauty standards.',url:'https://www.dove.com/us/en/campaigns/purpose/keep-beauty-real.html',hubs:['brand','promo','target'],tags:['Brand Purpose','Brand Positioning','Brand Identity','Public Relations','Campaign','Representation','Psychographics','Social Responsibility','Brand Equity','Target Market']},
{id:'nike-circular',company:'Nike',title:'Nike designs the ISPA Link Axis for disassembly and circularity',summary:'Nike redesigned footwear construction around fewer materials, recycled inputs and easier disassembly, showing how sustainability can shape product design itself.',url:'https://about.nike.com/en/newsroom/releases/nike-debuts-the-ispa-link-axis-an-exploration-into-circular-design',hubs:['fashion','mix','strategy'],tags:['Sustainability','Circular Fashion','Product Development','Textile','Materials','Product Life Cycle','Innovation','Competitive Advantage','Product Design','Recycling']}
].forEach(c=>{MCL_CASES.push(c);MCL_CASE_BY_ID[c.id]=c});
MCL_HUB_CASES.target.push('coke-share');MCL_HUB_CASES.brand.push('dove-real-beauty','coke-share');MCL_HUB_CASES.promo.push('coke-share','dove-real-beauty');MCL_HUB_CASES.mix.push('lego-ideas','nike-circular');MCL_HUB_CASES.fund.push('lego-ideas','shopify-entrepreneurship');MCL_HUB_CASES.ent.push('shopify-entrepreneurship','lego-ideas');MCL_HUB_CASES.strategy.push('shopify-entrepreneurship','nike-circular');MCL_HUB_CASES.fashion.push('nike-circular');
window.MCL_CASES=MCL_CASES;