// Real-company case study layer. Sources are official company/newsroom pages.
const MCL_CASES=[
{id:'nike-marketplace',company:'Nike',title:'Nike builds a connected digital + physical marketplace',summary:'Nike describes how its apps, stores, membership benefits and retail partners work together to create a more connected shopping experience.',url:'https://about.nike.com/en/newsroom/releases/nike-membership-digital-benefits',hubs:['mix','target','sell','fashion'],tags:['Distribution Channel','Omnichannel Retail','Customer Experience','CRM','Customer Loyalty','Place','Direct-to-Consumer','Retailing','Membership']},
{id:'nike-ai-shopping',company:'Nike',title:'Nike adds AI-assisted shopping through Google',summary:'Nike is connecting product discovery and checkout inside Google conversational shopping experiences while maintaining the direct consumer relationship.',url:'https://about.nike.com/en/newsroom/releases/nike-is-serving-athletes-faster-through-ai-powered-shopping-on-google',hubs:['mix','sell','strategy'],tags:['E-Commerce','Place','Distribution Channel','Customer Journey','Conversion','Innovation','Competitive Advantage','Technology']},
{id:'nike-snkrs',company:'Nike',title:'SNKRS Showcase gives sneaker fans early product access',summary:'Nike used its SNKRS ecosystem to reveal future footwear and apparel directly to sneaker fans before release.',url:'https://about.nike.com/en/newsroom/releases/nike-snkrs-showcase-official-images',hubs:['promo','brand','fashion','target'],tags:['Direct Marketing','Promotion','Product Launch','Early Access','Target Market','Brand Community','Scarcity','Product Assortment']},
{id:'spotify-wrapped',company:'Spotify',title:'Spotify turns listening data into the Wrapped global campaign',summary:'Spotify combines personalization, shareable data stories, outdoor media, fan experiences and partnerships to make Wrapped both a product experience and a global campaign.',url:'https://newsroom.spotify.com/2025-12-03/wrapped-marketing-campaign/',hubs:['fund','target','brand','promo','sem'],tags:['Personalization','Psychographics','Consumer Behavior','Brand Experience','Advertising','Engagement','Experiential Marketing','Campaign','Data','Segmentation']},
{id:'spotify-ai-dj',company:'Spotify',title:'Spotify uses personalization to build its AI DJ',summary:'Spotify explains how listening data and personalization shape a feature designed to deepen discovery and engagement.',url:'https://newsroom.spotify.com/2023-02-22/spotify-debuts-a-new-ai-dj-right-in-your-pocket/',hubs:['fund','target','strategy'],tags:['Consumer Behavior','Personalization','Market Research','Customer Data','Product','Innovation','Recommendation','Customer Experience']},
{id:'spotify-barca',company:'Spotify + FC Barcelona',title:'Spotify and FC Barcelona extend a culture-focused sponsorship',summary:'The partnership combines team assets, naming rights, artist jersey takeovers and fan activations to connect music, football and global audiences.',url:'https://newsroom.spotify.com/2025-10-17/spotify-fc-barcelona-extend-partnership-through-2030/',hubs:['sem','promo','brand'],tags:['Sponsorship','Naming Rights','Sponsorship Activation','Fan Engagement','Brand Collaboration','Co-Branding','Endorsement','Partnership']},
{id:'starbucks-rewards',company:'Starbucks',title:'Starbucks redesigns Rewards around tiers and personalization',summary:'Starbucks rebuilt its loyalty program with Green, Gold and Reserve levels, differentiated earning, personalized benefits and exclusive experiences.',url:'https://about.starbucks.com/press/2026/starbucks-unveils-reimagined-loyalty-program-to-deliver-more-meaningful-value-personalization-and-engagement-to-members/',hubs:['target','sell','promo','strategy'],tags:['Customer Loyalty','CRM','Personalization','Behavioral Segmentation','Sales Promotion','Customer Lifetime Value','Retention','Rewards','Frequency']},
{id:'starbucks-back',company:'Starbucks',title:'“Back to Starbucks” refocuses the brand and coffeehouse experience',summary:'Starbucks describes changes to marketing, menu, service flow and café experience intended to reconnect the company with its core brand identity.',url:'https://about.starbucks.com/stories/2025/how-back-to-starbucks-is-reshaping-every-aspect-of-the-coffeehouse-experience/',hubs:['brand','sell','strategy','mix'],tags:['Brand Identity','Brand Positioning','Rebranding','Customer Experience','Service Recovery','Operations','Product Mix','Competitive Advantage']},
{id:'starbucks-secret',company:'Starbucks',title:'Starbucks turns the “secret menu” into an official app feature',summary:'Starbucks formalized fan-created drink customization inside its app and paired it with a customer submission contest.',url:'https://about.starbucks.com/stories/2025/introducing-the-secret-menu-in-the-starbucks-app/',hubs:['promo','brand','sell','mix'],tags:['Sales Promotion','Contest','Customer Engagement','User-Generated Content','Product','Customization','App Marketing','Brand Community']},
{id:'mcd-minecraft',company:"McDonald's",title:'McDonald’s combines two fandoms in its Minecraft campaign',summary:'McDonald’s launched a large global campaign around A Minecraft Movie with themed meals, collectibles and experiences across many markets.',url:'https://corporate.mcdonalds.com/corpmcd/our-stories/article/minecraft-movie-global-meal.html',hubs:['promo','brand','sem','target'],tags:['Brand Collaboration','Promotion','Collectibles','Sales Promotion','Entertainment Marketing','Target Market','Fandom','Product Bundling','Limited-Time Offer']},
{id:'mcd-nostalgia',company:"McDonald's",title:'McDonald’s uses nostalgia and collaboration to reach adult fans',summary:'McDonald’s highlighted its Cactus Plant Flea Market collaboration as a way to connect adult customers with Happy Meal nostalgia and current culture.',url:'https://corporate.mcdonalds.com/corpmcd/our-stories/article/Q4-2022-earnings.html',hubs:['brand','promo','target'],tags:['Nostalgia Marketing','Brand Collaboration','Psychographics','Positioning','Customer Segment','Limited Edition','Brand Equity']},
{id:'walmart-omni',company:'Walmart',title:'Walmart uses stores as digital fulfillment nodes',summary:'Walmart reports strong e-commerce growth while emphasizing an omnichannel model in which stores support pickup and fast delivery.',url:'https://corporate.walmart.com/news/2026/05/21/walmart-releases-q1-fy27-earnings',hubs:['mix','strategy','fashion'],tags:['Omnichannel Retail','Distribution','Place','E-Commerce','Delivery','Competitive Advantage','Revenue','KPI','Retailing']},
{id:'patagonia-worn',company:'Patagonia',title:'Patagonia uses repair and resale to extend product life',summary:'Patagonia’s Worn Wear program connects repair, trade-in, used products and storytelling to its sustainability positioning and product philosophy.',url:'https://www.patagonia.com/stories/culture/worn-wear/',hubs:['fashion','brand','strategy'],tags:['Sustainability','Circular Fashion','Repair','Brand Purpose','Brand Positioning','Product Life Cycle','Customer Loyalty','Textile','Corporate Responsibility']},
{id:'netflix-ads',company:'Netflix',title:'Netflix builds an ad-supported tier around audience and advertiser value',summary:'Netflix explains the growth of its ad-supported plan and its effort to create advertising products around entertainment fandom and measurement.',url:'https://about.netflix.com/en/news/one-year-into-netflix-ads',hubs:['promo','mix','strategy','sem'],tags:['Advertising','Pricing Strategy','Market Segmentation','Media','Audience','Revenue Stream','Product Line','Fandom','Measurement']},
{id:'airbnb-q1',company:'Airbnb',title:'Airbnb expands pricing flexibility, experiences and event partnerships',summary:'Airbnb’s 2026 results describe pay-later options, pricing tools, services and experiences, event partnerships, international expansion and AI customer support.',url:'https://news.airbnb.com/airbnb-q1-2026-financial-results/',hubs:['ent','strategy','mix','sell','sem'],tags:['Business Model','Revenue Stream','Pricing Strategy','Dynamic Pricing','Customer Service','Market Expansion','Partnership','KPI','Innovation','Platform']}
];
const MCL_HUB_CASES={fund:['spotify-wrapped','spotify-ai-dj','walmart-omni'],target:['spotify-wrapped','starbucks-rewards','mcd-nostalgia','nike-snkrs'],mix:['nike-marketplace','nike-ai-shopping','walmart-omni','netflix-ads','airbnb-q1'],brand:['starbucks-back','spotify-wrapped','patagonia-worn','mcd-nostalgia'],promo:['mcd-minecraft','spotify-wrapped','nike-snkrs','starbucks-secret','netflix-ads'],sell:['starbucks-rewards','nike-marketplace','starbucks-back','airbnb-q1'],strategy:['walmart-omni','airbnb-q1','starbucks-back','patagonia-worn'],sem:['spotify-barca','mcd-minecraft','spotify-wrapped','airbnb-q1'],fashion:['patagonia-worn','nike-marketplace','nike-snkrs','walmart-omni'],ent:['airbnb-q1','spotify-ai-dj','starbucks-rewards','nike-ai-shopping']};
const MCL_CASE_BY_ID=Object.fromEntries(MCL_CASES.map(c=>[c.id,c]));
function mclHash(s){let h=0;for(let i=0;i<s.length;i++)h=(h*31+s.charCodeAt(i))>>>0;return h}
function mclCaseFor(term,hub){const low=String(term||'').toLowerCase();const tagged=MCL_CASES.filter(c=>c.tags.some(t=>low.includes(t.toLowerCase())||t.toLowerCase().includes(low)));if(tagged.length)return tagged[mclHash(low)%tagged.length];const ids=MCL_HUB_CASES[hub]||MCL_CASES.map(c=>c.id);return MCL_CASE_BY_ID[ids[mclHash(low+hub)%ids.length]]}
function mclCaseCard(c,term){return `<section class="caseStudy"><div class="caseTop"><div><div class="caseCompany">Real Company Case · ${esc(c.company)}</div><h3>${esc(c.title)}</h3></div><span class="chip">Case Study</span></div><p>${esc(c.summary)}</p><div class="caseWhy"><b>Concept lens: ${esc(term)}</b><br>As you read, identify the decision the company made and the evidence showing how it connects to <b>${esc(term)}</b>.</div><div class="casePrompt"><b>Case challenge:</b> What was the business objective? What tradeoff did the company accept? What would you measure to decide whether the move worked?</div><div class="actions"><a class="btn primary" href="${c.url}" target="_blank" rel="noopener noreferrer">Open company article ↗</a></div></section>`}
function mclFeaturedCases(hub){const ids=(MCL_HUB_CASES[hub]||[]).slice(0,3);return `<section class="card mclFeatured"><div class="ey">Real Company Cases</div><h2>See the hub in the wild</h2><div class="caseRack">${ids.map(id=>{const c=MCL_CASE_BY_ID[id];return `<div class="caseMini"><b>${esc(c.company)}</b><small>${esc(c.title)}</small><div class="actions"><a class="btn" href="${c.url}" target="_blank" rel="noopener noreferrer">Read case ↗</a></div></div>`}).join('')}</div></section>`}
function mclEnhance(){try{if(S.r==='term'&&S.t&&TB[S.t]&&!document.querySelector('.caseStudy')){const c=mclCaseFor(S.t,TB[S.t].h);const main=A.querySelector('.two>div');if(main)main.insertAdjacentHTML('beforeend',mclCaseCard(c,S.t));}if(S.r==='hub'&&S.h&&!document.querySelector('.mclFeatured')){const aside=A.querySelector('.two aside');if(aside)aside.insertAdjacentHTML('beforeend',mclFeaturedCases(S.h));}if(S.r==='home'&&!document.querySelector('.mclCaseHome')){const hero=A.querySelector('.hero');if(hero){const sec=document.createElement('section');sec.className='card mclCaseHome';sec.innerHTML=`<div class="ey">Case Library Layer</div><h2>Real companies throughout the encyclopedia</h2><p class="muted">Every concept entry now connects to a sourced company case. Cases intentionally repeat across related concepts so students can analyze the same business decision through different marketing lenses.</p><div class="caseRack">${MCL_CASES.slice(0,6).map(c=>`<div class="caseMini"><b>${esc(c.company)}</b><small>${esc(c.title)}</small></div>`).join('')}</div>`;hero.insertAdjacentElement('afterend',sec);}}}catch(e){console.warn('Case layer:',e)}}
const mclCaseObserver=new MutationObserver(()=>mclEnhance());mclCaseObserver.observe(document.getElementById('app'),{childList:true,subtree:true});setTimeout(mclEnhance,0);
window.MCL_CASES=MCL_CASES;