// Case mission + fresh-case rotation layer.
(function(){
const nav=document.querySelector('.nav');
const freshNav=document.createElement('button');freshNav.className='btn';freshNav.id='freshNav';freshNav.textContent='Fresh Cases';
const missionBtn=nav.querySelector('[data-go="missions"]');missionBtn?missionBtn.insertAdjacentElement('afterend',freshNav):nav.appendChild(freshNav);
function fmtDate(d){if(!d)return'';const x=new Date(d+'T12:00:00');return x.toLocaleDateString(undefined,{year:'numeric',month:'short',day:'numeric'})}
function weekSeed(){const d=new Date(),y=new Date(d.getFullYear(),0,1),day=Math.floor((d-y)/86400000);return d.getFullYear()*60+Math.ceil((day+y.getDay()+1)/7)}
function hash(s){let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0}
function caseLens(c){for(const tag of c.tags||[]){if(TB[tag])return tag}const hub=HB[(c.hubs||[])[0]];return hub?.[6]?.[0]?.[0]||'Marketing'}
function freshPool(){const cutoff=Date.now()-210*86400000;return MCL_CASES.filter(c=>c.date&&new Date(c.date+'T12:00:00').getTime()>=cutoff).sort((a,b)=>b.date.localeCompare(a.date))}
function rotateFresh(){const pool=freshPool().slice(0,32),seed=weekSeed();return pool.slice().sort((a,b)=>hash(a.id+seed)-hash(b.id+seed)).slice(0,10)}
function renderFresh(){S.r='fresh';document.querySelectorAll('.nav .btn').forEach(b=>b.classList.remove('on'));freshNav.classList.add('on');tip.classList.remove('show');const pool=freshPool(),show=rotateFresh(),latest=pool[0]?.date;A.innerHTML=`<section class="card hero freshHero"><div class="ey">Current Marketing News</div><h2>FRESH CASES</h2><p>A rotating set of recent real-company moves pulled from the sourced case library. The visible set changes weekly, while older cases stay available through the encyclopedia.</p><div class="stats"><div class="st"><b>${MCL_CASES.length}</b><small>Total sourced cases</small></div><div class="st"><b>${pool.length}</b><small>Cases from last 210 days</small></div><div class="st"><b>10</b><small>Rotating this week</small></div><div class="st"><b>${latest?fmtDate(latest):'—'}</b><small>Newest case date</small></div></div></section><section class="freshGrid">${show.map(c=>`<article class="freshCard"><div class="freshMeta"><span><span class="freshDot"></span>${fmtDate(c.date)}</span><span>${esc(c.company)}</span></div><h3>${esc(c.title)}</h3><p>${esc(c.summary)}</p><div class="freshConcepts">${(c.tags||[]).filter(t=>TB[t]).slice(0,4).map(t=>`<button class="chip" data-fresh-term="${esc(t)}">${esc(t)}</button>`).join('')}</div><div class="actions"><a class="btn primary" href="${c.url}" target="_blank" rel="noopener noreferrer">Open source ↗</a><button class="btn" data-fresh-term="${esc(caseLens(c))}">Analyze through ${esc(caseLens(c))}</button></div></article>`).join('')}</section>`;window.scrollTo({top:0,behavior:'smooth'})}
freshNav.onclick=renderFresh;
document.addEventListener('click',e=>{const x=e.target.closest('[data-fresh-term]');if(x){go('term',{t:x.dataset.freshTerm})}});
function caseForm(c,term){const id='case-'+c.id.replace(/[^a-z0-9]/gi,'-');return `<div class="caseMissionBox" data-casebox="${esc(c.id)}"><div class="ey">Case Mission · 75 XP</div><h3>Read it. Prove it. Recommend it.</h3><p class="muted">Use evidence from the source—not just the summary above.</p><div class="caseMissionGrid"><label>1. What did the company actually do?<textarea data-cf="evidence" placeholder="Specific evidence from the article..."></textarea></label><label>2. What business objective were they trying to achieve?<textarea data-cf="objective" placeholder="Awareness, sales, loyalty, expansion, differentiation..."></textarea></label><label>3. How does this case demonstrate ${esc(term)}?<textarea data-cf="connection" placeholder="Make the concept connection explicit..."></textarea></label><label>4. Your recommendation + one KPI<textarea data-cf="recommendation" placeholder="Keep, change, or extend the strategy—and how would you measure it?"></textarea></label></div><div class="actions"><button class="btn primary" data-case-save="${esc(c.id)}">Save Case Mission to Playbook</button></div></div>`}
function enhanceTermCase(){if(S.r!=='term'||!S.t||!TB[S.t])return;const card=document.querySelector('.caseStudy');if(!card||card.querySelector('[data-casebox]'))return;const c=mclCaseFor(S.t,TB[S.t].h);if(c.date&&!card.querySelector('.caseDate')){const top=card.querySelector('.caseCompany');if(top)top.insertAdjacentHTML('afterend',`<div class="caseDate">Source date: ${fmtDate(c.date)}</div>`)}card.insertAdjacentHTML('beforeend',caseForm(c,S.t))}
function updateHomeCount(){const box=document.querySelector('.mclCaseHome');if(!box)return;const h=box.querySelector('h2'),p=box.querySelector('p');if(h)h.innerHTML=`<span class="caseCount">${MCL_CASES.length}</span> sourced real-company cases`;if(p)p.textContent='Every concept entry connects to a sourced case, and Fresh Cases rotates newer company moves into view each week.'}
function saveCase(card){const vals={};card.querySelectorAll('[data-cf]').forEach(x=>vals[x.dataset.cf]=x.value.trim());if(Object.values(vals).some(v=>!v))return toast('Complete all four Case Mission decisions first.');const c=MCL_CASE_BY_ID[card.dataset.casebox],term=S.t,p=prof(),b=book();b.push({h:TB[term]?.h||c.hubs?.[0]||'fund',l:'case',title:`Case Mission: ${c.company} — ${term}`,text:`Evidence: ${vals.evidence}\n\nBusiness objective: ${vals.objective}\n\nConcept connection (${term}): ${vals.connection}\n\nRecommendation + KPI: ${vals.recommendation}`,date:new Date().toLocaleString(),student:p.n||'',period:p.p||'',caseId:c.id,xp:75});save(b);toast('Case Mission saved · +75 XP');card.querySelectorAll('textarea').forEach(x=>x.value='')}
document.addEventListener('click',e=>{const b=e.target.closest('[data-case-save]');if(b){const card=b.closest('[data-casebox]');if(card)saveCase(card)}});
const obs=new MutationObserver(()=>{enhanceTermCase();updateHomeCount()});obs.observe(A,{childList:true,subtree:true});setTimeout(()=>{enhanceTermCase();updateHomeCount()},0);
// Preserve the existing Playbook while correctly labeling Case Missions.
playbook=function(){let b=book(),p=prof(),caseN=b.filter(x=>x.l==='case').length,html='<section class="card hero"><div class="ey">Student Portfolio</div><h2>MY PLAYBOOK</h2><p>Mission work and article analyses saved on this browser appear here.</p><div class="stats"><div class="st"><b>'+b.length+'</b><small>Total artifacts</small></div><div class="st"><b>'+caseN+'</b><small>Case analyses</small></div><div class="st"><b>'+H.filter(h=>comp(h[0])==100).length+'</b><small>Hubs mastered</small></div><div class="st"><b>'+Object.keys(scores()).length+'</b><small>Quick checks</small></div></div></section>';html+='<section class="card"><div class="profile"><input id="pn" class="field" placeholder="Student name" value="'+esc(p.n||'')+'"><select id="pp" class="field"><option value="">Period</option>';[1,2,3,4,5,6,7].forEach(x=>html+='<option '+(p.p==x?'selected':'')+'>'+x+'</option>');html+='</select><button id="ps" class="btn primary">Save</button></div><div class="actions"><button id="export" class="btn">Export .txt</button><button id="clearbook" class="btn">Clear Playbook</button></div></section>';if(!b.length)html+='<div class="card muted">No mission work saved yet.</div>';else b.slice().reverse().forEach(x=>{const label=x.l==='m'?'Field Drill':x.l==='h'?'Boss Mission':'Case Analysis';html+='<article class="play"><div class="ey">'+esc(HB[x.h]?.[1]||'Marketing')+' · '+label+'</div><h3>'+esc(x.title)+'</h3><small class="muted">'+esc(x.date)+(x.student?' · '+esc(x.student):'')+(x.period?' · Period '+esc(x.period):'')+(x.xp?' · '+x.xp+' XP':'')+'</small><p>'+esc(x.text).replace(/\n/g,'<br>')+'</p></article>'});A.innerHTML=html};
exportbook=function(){const b=book(),p=prof();let txt=`MARKETING PLAYBOOK\nStudent: ${p.n||''}\nPeriod: ${p.p||''}\nArtifacts: ${b.length}\nCase analyses: ${b.filter(x=>x.l==='case').length}\n\n`;b.forEach((x,i)=>{const label=x.l==='m'?'Field Drill':x.l==='h'?'Boss Mission':'Case Analysis';txt+=`${i+1}. ${label} — ${x.title}\n${x.date}\n${x.text}\n\n`});const blob=new Blob([txt],{type:'text/plain'}),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=((p.n||'Student').replace(/[^a-z0-9]+/gi,'_')+'_Marketing_Playbook.txt');a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)};
})();