// Cleaner visual learning layer. Keeps the full system, reveals depth progressively.
(function(){
const iconByHub={fund:'◎',target:'⌖',mix:'◫',brand:'◇',promo:'◉',sell:'↗',strategy:'△',sem:'★',fashion:'✦',ent:'◆'};
function routeHub(){return S.h&&HB[S.h]?HB[S.h]:null}
function nodeButton(t){return `<button class="visualNode" data-termopen="${esc(t[0])}" data-hoverterm="${esc(t[0])}"><b>${esc(t[0])}</b><small>${esc(t[1])}</small></button>`}
function enhanceHub(){
 if(S.r!=='hub')return;const h=routeHub();if(!h)return;const main=A.querySelector('.two>div');if(!main)return;
 const hero=main.querySelector('.hero');if(hero&&!main.querySelector('.cleanVisual')){const picks=h[6].slice(0,4);hero.insertAdjacentHTML('afterend',`<section class="cleanVisual"><div class="cleanVisualHead"><div><div class="ey">Visual Explanation</div><h3>${iconByHub[h[0]]||'◎'} ${esc(h[1])} at a glance</h3></div><p>Start with the big idea, then drill into the four concepts below.</p></div><div class="visualMap"><div class="visualCenter">${esc(h[1])}</div><div class="visualBranches">${picks.map(nodeButton).join('')}</div></div></section>`)}
 const tg=main.querySelector('.termgrid');if(tg&&!tg.dataset.clean){tg.dataset.clean='1';const terms=[...tg.children];if(terms.length>6){terms.slice(6).forEach(x=>x.style.display='none');const btn=document.createElement('button');btn.className='btn cleanShowTerms';btn.textContent=`Show all ${terms.length} concepts`;btn.onclick=()=>{const hidden=terms.slice(6).some(x=>x.style.display==='none');terms.slice(6).forEach(x=>x.style.display=hidden?'':'none');btn.textContent=hidden?'Show fewer concepts':`Show all ${terms.length} concepts`};tg.insertAdjacentElement('afterend',btn)}}
 enhanceMissions();
}
function enhanceTerm(){
 if(S.r!=='term'||!S.t||!TB[S.t])return;const t=TB[S.t],h=HB[t.h],two=A.querySelector('.two'),main=two?.querySelector(':scope>div');if(!main)return;
 let hero=main.querySelector(':scope>.hero');if(hero&&!main.querySelector('.cleanTermHero')){const shell=document.createElement('div');shell.className='cleanTermHero';hero.insertAdjacentElement('beforebegin',shell);shell.appendChild(hero);const rel=relatedTermNames(t.n).slice(0,3);const visual=document.createElement('section');visual.className='termVisualCard';visual.innerHTML=`<div class="ey">Visual Context</div><div class="termVisualCore">${esc(t.n)}</div><div class="termVisualFlow">${rel.map(n=>`<button data-termopen="${esc(n)}">→ ${esc(n)}</button>`).join('')}</div>`;shell.appendChild(visual)}
 const cards=[...main.querySelectorAll(':scope>.card')];const deep=cards.filter(c=>{const ey=c.querySelector('.ey')?.textContent||'';return /Why it connects|60-Second Try It/i.test(ey)});if(deep.length&&!main.querySelector('.cleanMore')){const det=document.createElement('details');det.className='cleanMore';det.innerHTML='<summary>Explore more connections and practice</summary><div class="cleanMoreBody"></div>';const anchor=deep[0];anchor.insertAdjacentElement('beforebegin',det);const body=det.querySelector('.cleanMoreBody');deep.forEach(c=>body.appendChild(c))}
 const caseBox=main.querySelector('.caseStudy .caseMissionBox');if(caseBox&&!caseBox.closest('.cleanCaseMore')){const d=document.createElement('details');d.className='cleanMore cleanCaseMore';d.innerHTML='<summary>Analyze this case · 75 XP</summary><div class="cleanMoreBody"></div>';caseBox.insertAdjacentElement('beforebegin',d);d.querySelector('.cleanMoreBody').appendChild(caseBox)}
}
function missionProgress(m){
 const decisions=[...m.querySelectorAll('.decision')],tas=[...m.querySelectorAll('[data-mfield]')];if(!tas.length)return;let filled=tas.filter(x=>x.value.trim()).length;
 decisions.forEach((d,i)=>d.classList.toggle('visible',i===0||tas.slice(0,i).every(x=>x.value.trim())));
 m.classList.toggle('pressure-ready',filled>=Math.min(2,tas.length));m.classList.toggle('complete-ready',filled===tas.length);
 const bar=m.querySelector('.missionProgress span'),stage=m.querySelector('.missionStage');if(bar)bar.style.width=Math.round(filled/tas.length*100)+'%';if(stage)stage.textContent=`${filled}/${tas.length} decisions complete`;
}
function enhanceMissions(){document.querySelectorAll('.gameMission').forEach(m=>{if(m.dataset.cleanMission)return;m.dataset.cleanMission='1';const brief=m.querySelector('.briefing');if(!brief)return;const launch=document.createElement('div');launch.className='missionLaunch';launch.innerHTML='<div><b>Ready for the challenge?</b><div class="missionStage">0 decisions complete</div></div><div class="missionProgress"><span></span></div><button class="btn primary" data-clean-start>Start Mission</button>';brief.insertAdjacentElement('afterend',launch);const hasDraft=[...m.querySelectorAll('[data-mfield]')].some(x=>x.value.trim());if(hasDraft){m.classList.add('mission-active');launch.querySelector('[data-clean-start]').textContent='Hide decisions'}missionProgress(m)})}
function enhanceHome(){if(S.r!=='home')return;A.querySelectorAll('.hub').forEach((b,i)=>{if(b.dataset.cleanIcon)return;b.dataset.cleanIcon='1';const id=H[i]?.[0],h3=b.querySelector('h3');if(h3)h3.insertAdjacentHTML('afterbegin',`<span style="color:var(--c);margin-right:8px">${iconByHub[id]||'◎'}</span>`)})}
function enhanceFresh(){if(S.r!=='fresh')return;const cards=[...A.querySelectorAll('.freshCard')];cards.forEach((c,i)=>{if(c.dataset.cleanFresh)return;c.dataset.cleanFresh='1';if(i>=6)c.style.display='none'});if(cards.length>6&&!A.querySelector('.cleanFreshMore')){const b=document.createElement('button');b.className='btn cleanFreshMore';b.textContent='Show 4 more current cases';b.onclick=()=>{const hidden=cards.slice(6).some(c=>c.style.display==='none');cards.slice(6).forEach(c=>c.style.display=hidden?'':'none');b.textContent=hidden?'Show fewer cases':'Show 4 more current cases'};A.querySelector('.freshGrid')?.insertAdjacentElement('afterend',b)}}
function enhance(){try{enhanceHome();enhanceHub();enhanceTerm();enhanceFresh()}catch(e){console.warn('Clean UI:',e)}}
document.addEventListener('click',e=>{const b=e.target.closest('[data-clean-start]');if(!b)return;const m=b.closest('.gameMission');if(!m)return;m.classList.toggle('mission-active');b.textContent=m.classList.contains('mission-active')?'Hide decisions':'Start Mission';missionProgress(m)});
document.addEventListener('input',e=>{if(e.target.matches('[data-mfield]'))missionProgress(e.target.closest('.gameMission'))});
const obs=new MutationObserver(()=>enhance());obs.observe(A,{childList:true,subtree:true});setTimeout(enhance,0);
})();