(()=>{
'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={startedAt:new Date().toISOString(),score:0,trust:3,stage:0,inboxCorrect:0,inboxTotal:6,hazardsCorrect:0,hazardsTotal:4,badges:0,hits:0,ratings:{fun:0,clarity:0,gameFeel:0},events:[]};
const screens=['title','brief','inbox','hazard','elevator','review'];
let currentScreen='title',screenEntered=Date.now(),screenTimes=[];
function log(action,result){state.events.push({at:new Date().toISOString(),screen:currentScreen,action,result});}
function show(name){screenTimes.push({screen:currentScreen,durationMs:Date.now()-screenEntered});currentScreen=name;screenEntered=Date.now();screens.forEach(n=>$('#'+n+'Screen').classList.toggle('hidden',n!==name));const labels={title:'ACTION LAB',brief:'BRIEFING',inbox:'INBOX ATTACK',hazard:'SAFETY SWEEP',elevator:'ELEVATOR RUN',review:'REVIEW'};$('#stageLabel').textContent=labels[name];window.scrollTo({top:0,behavior:'instant'});}
function hud(){ $('#scoreHud').textContent=state.score;$('#trustHud').textContent=state.trust;$('#stageHud').textContent=Math.min(state.stage,3)+'/3'; }
function addScore(n){state.score=Math.max(0,state.score+n);hud();}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1300)}
$('#startBtn').onclick=()=>{log('START EMERGENCY');show('brief')};
$('#clockBtn').onclick=()=>{log('CLOCK IN');state.stage=1;hud();show('inbox')};
const mails=[
 {from:'Unknown Vendor',subject:'Payroll verification link',body:'Confirm your password before 8:10 AM.',dir:'down'},
 {from:'Shift Manager',subject:'Customer waiting at desk',body:'Needs a replacement receipt now.',dir:'right'},
 {from:'Facilities',subject:'Quarterly drill planning',body:'Choose a date for next month.',dir:'up'},
 {from:'System Bot',subject:'You won a gift card',body:'Click immediately to claim.',dir:'left'},
 {from:'Team Lead',subject:'Can you cover register 2?',body:'Line is growing right now.',dir:'right'},
 {from:'Security',subject:'Suspicious login detected',body:'Forward the alert through the official channel.',dir:'down'}
];
let mailIndex=0,inboxSeconds=32,inboxInterval=null,activeMail=null,dragStart=null;
function renderMail(){if(mailIndex>=mails.length){finishInbox();return}const m=mails[mailIndex];const card=document.createElement('article');card.className='mail-card';card.innerHTML=`<div class="from">From: ${m.from}</div><h3>${m.subject}</h3><p>${m.body}</p>`;$('#mailStack').append(card);activeMail=card;card.addEventListener('pointerdown',e=>{dragStart={x:e.clientX,y:e.clientY};card.setPointerCapture(e.pointerId);card.classList.add('dragging')});card.addEventListener('pointermove',e=>{if(!dragStart)return;const dx=e.clientX-dragStart.x,dy=e.clientY-dragStart.y;card.style.transform=`translate(${dx}px,${dy}px) rotate(${dx/25}deg)`});card.addEventListener('pointerup',e=>{if(!dragStart)return;const dx=e.clientX-dragStart.x,dy=e.clientY-dragStart.y;card.classList.remove('dragging');dragStart=null;const dir=Math.abs(dx)>Math.abs(dy)?(dx<0?'left':'right'):(dy<0?'up':'down');if(Math.max(Math.abs(dx),Math.abs(dy))<55){card.style.transform='';return}resolveSwipe(dir)});}
function flashMail(good,text){const f=$('#mailFlash');f.className='flash '+(good?'good':'bad');f.textContent=text;void f.offsetWidth;f.classList.add('show')}
function resolveSwipe(dir){if(!activeMail)return;const m=mails[mailIndex],correct=dir===m.dir;log('SWIPE '+dir,correct?'success':'failure');if(correct){state.inboxCorrect++;addScore(100);flashMail(true,'Clean sort')}else{state.trust=Math.max(0,state.trust-1);addScore(-35);inboxSeconds=Math.max(0,inboxSeconds-3);flashMail(false,'Wrong lane')}activeMail.style.opacity='0';activeMail.style.transform=`translate(${dir==='left'?-600:dir==='right'?600:0}px,${dir==='up'?-600:dir==='down'?600:0}px) rotate(20deg)`;const old=activeMail;activeMail=null;setTimeout(()=>{old.remove();mailIndex++;renderMail()},170);hud()}
$$('[data-swipe]').forEach(b=>b.onclick=()=>resolveSwipe(b.dataset.swipe));
$('#startInboxBtn').onclick=()=>{log('START INBOX');$('#inboxReady').classList.add('hidden');$('#inboxGame').classList.remove('hidden');$('#inboxTimer').textContent=inboxSeconds;renderMail();inboxInterval=setInterval(()=>{inboxSeconds--;$('#inboxTimer').textContent=inboxSeconds;if(inboxSeconds<=8)$('#inboxTimer').classList.add('urgent');if(inboxSeconds<=0)finishInbox()},1000)};
function finishInbox(){if(inboxInterval){clearInterval(inboxInterval);inboxInterval=null}if(activeMail){activeMail.remove();activeMail=null}log('FINISH INBOX',`${state.inboxCorrect}/${state.inboxTotal}`);state.stage=2;hud();setTimeout(()=>show('hazard'),450)}
const tools=[{id:'cone',icon:'🚧',label:'Block Area'},{id:'mop',icon:'🧹',label:'Clean Spill'},{id:'lift',icon:'👥',label:'Team Lift'},{id:'report',icon:'📞',label:'Report Power'}];
const hazards=[
 {id:'spill',tool:'mop',icon:'💧',label:'Spill',x:8,y:58},
 {id:'box',tool:'lift',icon:'📦',label:'Heavy box',x:58,y:54},
 {id:'wire',tool:'cone',icon:'🔌',label:'Open cable',x:68,y:8},
 {id:'spark',tool:'report',icon:'⚡',label:'Sparking outlet',x:32,y:25}
];
let hazardSeconds=35,hazardInterval=null,dragTool=null,ghost=null;
function buildHazards(){const box=$('#toolbox'),map=$('#officeMap');box.innerHTML='';map.querySelectorAll('.hazard').forEach(n=>n.remove());tools.forEach(t=>{const el=document.createElement('div');el.className='tool';el.dataset.tool=t.id;el.innerHTML=`<span>${t.icon}</span><small>${t.label}</small>`;box.append(el);el.addEventListener('pointerdown',e=>startToolDrag(e,t,el))});hazards.forEach(h=>{const el=document.createElement('div');el.className='hazard';el.dataset.hazard=h.id;el.dataset.tool=h.tool;el.style.left=h.x+'%';el.style.top=h.y+'%';el.innerHTML=`<div><span>${h.icon}</span>${h.label}</div>`;map.append(el)})}
function startToolDrag(e,t,source){if(source.classList.contains('used'))return;dragTool={...t,source};ghost=source.cloneNode(true);ghost.className='tool drag-ghost';document.body.append(ghost);moveGhost(e);source.setPointerCapture(e.pointerId);source.onpointermove=moveGhost;source.onpointerup=endToolDrag}
function moveGhost(e){if(ghost){ghost.style.left=e.clientX+'px';ghost.style.top=e.clientY+'px'}}
function endToolDrag(e){if(!dragTool)return;const target=document.elementFromPoint(e.clientX,e.clientY)?.closest('.hazard');const tool=dragTool;tool.source.onpointermove=null;tool.source.onpointerup=null;ghost?.remove();ghost=null;dragTool=null;if(!target){$('#hazardStatus').textContent='Missed the hazard. Try again.';return}if(target.dataset.tool===tool.id&&!target.classList.contains('solved')){target.classList.add('solved');target.innerHTML=`<div><span>✅</span>${tool.label}</div>`;tool.source.classList.add('used');state.hazardsCorrect++;addScore(125);$('#hazardStatus').textContent='Hazard cleared. Keep moving.';log('SOLVE '+target.dataset.hazard,'success');if(state.hazardsCorrect>=state.hazardsTotal)setTimeout(finishHazards,450)}else{state.trust=Math.max(0,state.trust-1);addScore(-30);$('#hazardStatus').textContent='Wrong response tool. Reassess the hazard.';log('TOOL '+tool.id+' ON '+target.dataset.hazard,'failure');hud()}}
$('#startHazardBtn').onclick=()=>{log('START SAFETY SWEEP');$('#hazardReady').classList.add('hidden');$('#hazardGame').classList.remove('hidden');buildHazards();$('#hazardTimer').textContent=hazardSeconds;hazardInterval=setInterval(()=>{hazardSeconds--;$('#hazardTimer').textContent=hazardSeconds;if(hazardSeconds<=8)$('#hazardTimer').classList.add('urgent');if(hazardSeconds<=0)finishHazards()},1000)};
function finishHazards(){if(hazardInterval){clearInterval(hazardInterval);hazardInterval=null}log('FINISH SAFETY',`${state.hazardsCorrect}/${state.hazardsTotal}`);state.stage=3;hud();setupElevator();show('elevator')}
const canvas=$('#gameCanvas'),ctx=canvas.getContext('2d');let running=false,raf=0,last=0,elapsed=0,spawnClock=0,badgeClock=0;let player={x:330,y:700,w:70,h:70,v:0};let objects=[];let leftHeld=false,rightHeld=false;let elevatorSeconds=28;
function setupElevator(){const shield=state.inboxCorrect>=5,path=state.hazardsCorrect>=3;$('#elevatorModifier').textContent=`${shield?'Cyber Shield active: fewer hazards.':'No Cyber Shield: normal hazard rate.'} ${path?'Clear Path active: wider movement lane.':'Unsafe path: narrower lane.'}`;canvas.width=760;canvas.height=820;player={x:345,y:710,w:70,h:70,v:0};objects=[];drawArcade()}
function startArcade(){if(running)return;running=true;$('#arcadeOverlay').classList.add('hidden');$('#elevatorTimer').textContent=elevatorSeconds;last=performance.now();log('START ELEVATOR RUN');raf=requestAnimationFrame(loop)}
$('#startElevatorBtn').onclick=startArcade;
function bindHold(el,set){el.addEventListener('pointerdown',e=>{e.preventDefault();set(true);el.setPointerCapture(e.pointerId)});el.addEventListener('pointerup',()=>set(false));el.addEventListener('pointercancel',()=>set(false))}
bindHold($('#leftBtn'),v=>leftHeld=v);bindHold($('#rightBtn'),v=>rightHeld=v);
addEventListener('keydown',e=>{if(e.key==='ArrowLeft')leftHeld=true;if(e.key==='ArrowRight')rightHeld=true});addEventListener('keyup',e=>{if(e.key==='ArrowLeft')leftHeld=false;if(e.key==='ArrowRight')rightHeld=false});
function spawn(type){const clearPath=state.hazardsCorrect>=3;const minX=clearPath?30:110,maxX=clearPath?660:580;objects.push({type,x:minX+Math.random()*(maxX-minX),y:-70,w:type==='badge'?48:60,h:type==='badge'?48:60,vy:type==='badge'?250:330+Math.random()*120})}
function hit(a,b){return a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y}
function loop(now){const dt=Math.min(.035,(now-last)/1000);last=now;elapsed+=dt;spawnClock+=dt;badgeClock+=dt;elevatorSeconds=Math.max(0,28-Math.floor(elapsed));$('#elevatorTimer').textContent=elevatorSeconds;if(elevatorSeconds<=8)$('#elevatorTimer').classList.add('urgent');const speed=leftHeld?-430:rightHeld?430:0;player.x+=speed*dt;const clearPath=state.hazardsCorrect>=3;player.x=Math.max(clearPath?10:90,Math.min(clearPath?680:600,player.x));const hazardRate=state.inboxCorrect>=5?1.02:.72;if(spawnClock>hazardRate){spawnClock=0;spawn('hazard')}if(badgeClock>2.25){badgeClock=0;spawn('badge')}objects.forEach(o=>o.y+=o.vy*dt);for(let i=objects.length-1;i>=0;i--){const o=objects[i];if(hit(player,o)){if(o.type==='badge'){state.badges++;addScore(160);log('COLLECT BADGE','success')}else{state.hits++;state.trust=Math.max(0,state.trust-1);addScore(-70);log('HIT HAZARD','failure');hud()}objects.splice(i,1)}else if(o.y>850)objects.splice(i,1)}drawArcade();if(elapsed>=28){finishArcade();return}raf=requestAnimationFrame(loop)}
function drawArcade(){ctx.clearRect(0,0,canvas.width,canvas.height);const g=ctx.createLinearGradient(0,0,0,820);g.addColorStop(0,'#07111c');g.addColorStop(1,'#02060b');ctx.fillStyle=g;ctx.fillRect(0,0,760,820);ctx.strokeStyle='#20394e';ctx.lineWidth=5;for(let x=0;x<760;x+=95){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,820);ctx.stroke()}ctx.fillStyle='#b7ff47';ctx.shadowColor='#b7ff47';ctx.shadowBlur=18;ctx.fillRect(player.x,player.y,player.w,player.h);ctx.shadowBlur=0;ctx.fillStyle='#07101d';ctx.font='900 34px system-ui';ctx.fillText('YOU',player.x+3,player.y+47);objects.forEach(o=>{if(o.type==='badge'){ctx.fillStyle='#4be2ff';ctx.shadowColor='#4be2ff';ctx.shadowBlur=16;ctx.fillRect(o.x,o.y,o.w,o.h);ctx.shadowBlur=0;ctx.fillStyle='#07101d';ctx.font='900 30px system-ui';ctx.fillText('ID',o.x+7,o.y+35)}else{ctx.fillStyle='#ff4e45';ctx.fillRect(o.x,o.y,o.w,o.h);ctx.fillStyle='#fff';ctx.font='36px system-ui';ctx.fillText('⚠',o.x+10,o.y+43)}})}
function finishArcade(){running=false;cancelAnimationFrame(raf);log('FINISH ELEVATOR',`badges:${state.badges},hits:${state.hits}`);showReview()}
function showReview(){state.stage=3;hud();show('review');$('#finalScore').textContent=state.score;$('#finalInbox').textContent=`${state.inboxCorrect}/${state.inboxTotal}`;$('#finalHazards').textContent=`${state.hazardsCorrect}/${state.hazardsTotal}`;$('#reviewTitle').textContent=state.badges>=3&&state.hits<=2?'Promotion route opened':'Floor survived — barely';const shield=state.inboxCorrect>=5,path=state.hazardsCorrect>=3;$('#chainResults').innerHTML=`<article><strong>${shield?'CYBER SHIELD UNLOCKED':'CYBER SHIELD MISSED'}</strong><span>${shield?'Strong inbox decisions reduced the falling-hazard rate.':'Inbox errors left the escape route exposed.'}</span></article><article><strong>${path?'CLEAR PATH UNLOCKED':'PATH RESTRICTED'}</strong><span>${path?'Safety performance widened the movement lane.':'Unresolved hazards narrowed the movement lane.'}</span></article><article><strong>BADGES: ${state.badges}</strong><span>Collected access badges converted directly into score.</span></article><article><strong>HITS: ${state.hits}</strong><span>Each collision cost trust and score immediately.</span></article>`}
$$('[data-rating]').forEach(group=>{for(let i=1;i<=5;i++){const b=document.createElement('button');b.textContent=i;b.onclick=()=>{const k=group.dataset.rating;state.ratings[k]=i;[...group.children].forEach((x,j)=>x.classList.toggle('selected',j<i));log('RATE '+k,i)};group.append(b)}});
$('#replayBtn').onclick=()=>location.reload();
$('#exportBtn').onclick=()=>{screenTimes.push({screen:currentScreen,durationMs:Date.now()-screenEntered});const payload={version:1,build:'action-lab-0.1',id:crypto.randomUUID(),startedAt:state.startedAt,finishedAt:new Date().toISOString(),viewport:{width:innerWidth,height:innerHeight,userAgent:navigator.userAgent},results:{score:state.score,trust:state.trust,inboxCorrect:state.inboxCorrect,inboxTotal:state.inboxTotal,hazardsCorrect:state.hazardsCorrect,hazardsTotal:state.hazardsTotal,badges:state.badges,hits:state.hits},chainReactions:{cyberShield:state.inboxCorrect>=5,clearPath:state.hazardsCorrect>=3},feedback:{...state.ratings,comment:$('#comment').value.trim()},screens:screenTimes,events:state.events};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`wrs-action-lab-${payload.id}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500);toast('Feedback JSON exported');log('EXPORT JSON')};
hud();
})();
