const SUPABASE_URL='https://dtlyxqjkkuxltixokono.supabase.co';
const SUPABASE_KEY='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR0bHl4cWpra3V4bHRpeG9rb25vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODc2OTAwMTUsImV4cCI6MjEwMzI2NjAxNX0.0SAlJEmuOQE4SMzOEwIGChjnlqLsAK2IBcTdIQBXIxQ';
const headers={'apikey':SUPABASE_KEY,'Authorization':'Bearer '+SUPABASE_KEY,'Content-Type':'application/json'};
let classes=[], currentClass=null, profiles=[], selectedProfile=null, editMode=false;
const $=id=>document.getElementById(id);
async function api(path,opts={}){const r=await fetch(SUPABASE_URL+path,{...opts,headers:{...headers,...(opts.headers||{})}});let data=null;const text=await r.text();if(text){try{data=JSON.parse(text)}catch{data=text}}if(!r.ok)throw new Error(data?.message||data?.error_description||data?.hint||'Request failed');return data}
function initials(p){return ((p.first_name?.[0]||'')+(p.last_initial||'')).toUpperCase()}
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function goTop(){requestAnimationFrame(()=>window.scrollTo({top:0,left:0,behavior:'instant'}))}
function setStatus(text,live=true){$('status').innerHTML=`<span class="statusdot" style="${live?'':'background:#b42318;box-shadow:0 0 0 4px rgba(180,35,24,.08)'}"></span><span>${esc(text)}</span>`}
async function init(){try{classes=await api('/rest/v1/classes?select=id,slug,name,course,period&order=period');setStatus('Live');landing()}catch(e){setStatus('Connection issue',false);$('app').innerHTML='<div class="loading">Could not connect to ClassSpace. '+esc(e.message)+'</div>'}}
function landing(){currentClass=null;goTop();$('app').innerHTML=`<section class="hero"><div class="heroinner"><small>✦ Your class. Your people. Your space.</small><h1>Welcome to ClassSpace.</h1><p>Build a profile, discover what your classmates are into, and find people you might actually want to work with.</p><div class="hero-note">Profiles are visible only inside ClassSpace — no social media account needed.</div></div></section><main class="wrap"><div class="sectionhead"><div><div class="eyebrow">Get started</div><h2>Choose your class</h2></div><p>Pick your period to enter its directory. Your profile will live in the class you choose.</p></div><div class="classes">${classes.map(c=>`<button class="classcard" onclick="openClass('${esc(c.slug)}')"><div class="period">${esc(c.period.replace(/[^0-9]/g,''))}</div><div><strong>${esc(c.name)}</strong><span>${esc(c.course)}</span></div><div class="chev">›</div></button>`).join('')}</div></main>`}
async function openClass(slug){currentClass=classes.find(c=>c.slug===slug);goTop();$('app').innerHTML='<div class="loading">Loading class…</div>';await loadProfiles();renderDirectory();goTop()}
async function loadProfiles(){profiles=await api('/rest/v1/profiles?select=id,class_id,first_name,last_initial,avatar_url,display_color,favorite_music,favorite_entertainment,favorite_food,interests,skill,career_goal,talk_to_me_about,random_fact,year_goal,published,updated_at&class_id=eq.'+encodeURIComponent(currentClass.id)+'&published=eq.true&order=first_name.asc')}
function renderDirectory(){const cards=profiles.length?profiles.map(profileCard).join(''):`<div class="empty"><h3>No profiles yet.</h3><p>Be the first person in ${esc(currentClass.name)} to create one.</p><button class="btn primary" style="margin-top:10px" onclick="openCreate()">Create the first profile</button></div>`;$('app').innerHTML=`<section class="dhero"><div class="drow"><div><div class="classpill">${esc(currentClass.name)} · Class directory</div><h1>Find your people.</h1><p>Browse interests, strengths, favorites, and career goals. Find something you have in common — or something completely different.</p></div><div class="heroactions"><button class="btn white" onclick="openCreate()">+ Create my profile</button><button class="btn ghost-dark" onclick="landing()">Change class</button></div></div></section><main class="wrap"><div class="directorybar"><div class="searchwrap"><span class="searchicon">⌕</span><input class="search" id="search" placeholder="Search names, interests, skills, careers…" oninput="filterCards()"></div><div class="countpill">${profiles.length} profile${profiles.length===1?'':'s'}</div></div><div class="people" id="people">${cards}</div></main>`}
function profileCard(p){const tags=(p.interests||[]).slice(0,4).map(t=>`<span class="tag">${esc(t)}</span>`).join('');return `<article class="card"><div class="cardtop"><div class="avatar">${esc(initials(p))}</div><span class="smallbadge">ClassSpace</span></div><h3>${esc(p.first_name)} ${esc(p.last_initial)}.</h3><div class="career">${esc(p.career_goal||'Still figuring it out')}</div><div class="tags">${tags}</div><div class="cardfacts"><div class="minifact"><small>Good at</small><strong>${esc(p.skill||'—')}</strong></div><div class="minifact"><small>Favorite food</small><strong>${esc(p.favorite_food||'—')}</strong></div></div>${p.talk_to_me_about?`<div class="talk"><small>Talk to me about</small><span>${esc(p.talk_to_me_about)}</span></div>`:''}<div class="cardactions"><button class="linkbtn" onclick="viewProfile('${p.id}')">View full profile</button><span class="arrowbtn">›</span></div></article>`}
function filterCards(){const q=($('search').value||'').toLowerCase().trim();const f=profiles.filter(p=>[p.first_name,p.last_initial,p.career_goal,p.skill,p.favorite_music,p.favorite_entertainment,p.favorite_food,p.talk_to_me_about,...(p.interests||[])].join(' ').toLowerCase().includes(q));$('people').innerHTML=f.length?f.map(profileCard).join(''):'<div class="empty"><h3>No matches.</h3><p>Try another name, interest, skill, or career.</p></div>'}
function openCreate(){editMode=false;selectedProfile=null;$('formEyebrow').textContent='CREATE PROFILE';$('formTitle').textContent='Build your ClassSpace profile';$('saveBtn').textContent='Publish profile';$('profileForm').reset();$('formMessage').innerHTML='';$('formModal').classList.add('open');document.body.classList.add('modal-open')}
function closeForm(){$('formModal').classList.remove('open');document.body.classList.remove('modal-open')}
function collectProfile(){return{first_name:$('first_name').value.trim(),last_initial:$('last_initial').value.trim().toUpperCase(),favorite_music:$('favorite_music').value.trim(),favorite_entertainment:$('favorite_entertainment').value.trim(),favorite_food:$('favorite_food').value.trim(),interests:$('interests').value.split(',').map(x=>x.trim()).filter(Boolean).slice(0,8),skill:$('skill').value.trim(),career_goal:$('career_goal').value.trim(),talk_to_me_about:$('talk_to_me_about').value.trim(),random_fact:$('random_fact').value.trim(),year_goal:$('year_goal').value.trim()}}
async function saveProfile(e){e.preventDefault();const pin=$('pin').value.trim();if(!/^\d{4}$/.test(pin)){showFormError('Your edit PIN must be exactly 4 numbers.');return}const payload=collectProfile();$('saveBtn').disabled=true;$('saveBtn').textContent='Saving…';try{if(editMode){await api('/rest/v1/rpc/update_classspace_profile',{method:'POST',body:JSON.stringify({p_profile_id:selectedProfile.id,p_pin:pin,p_profile:payload})})}else{await api('/rest/v1/rpc/create_classspace_profile',{method:'POST',body:JSON.stringify({p_class_slug:currentClass.slug,p_pin:pin,p_profile:payload})})}closeForm();await loadProfiles();renderDirectory();goTop()}catch(err){showFormError(err.message.includes('Incorrect PIN')?'That PIN does not match this profile.':err.message)}finally{$('saveBtn').disabled=false;$('saveBtn').textContent=editMode?'Save changes':'Publish profile'}}
function showFormError(msg){$('formMessage').innerHTML=`<div class="message err">${esc(msg)}</div>`}
function viewProfile(id){selectedProfile=profiles.find(p=>p.id===id);$('viewName').textContent=`${selectedProfile.first_name} ${selectedProfile.last_initial}.`;$('viewAvatar').textContent=initials(selectedProfile);$('viewCareer').textContent=selectedProfile.career_goal||'Still figuring it out';$('viewTags').innerHTML=(selectedProfile.interests||[]).map(t=>`<span class="tag">${esc(t)}</span>`).join('');const facts=[['Favorite music',selectedProfile.favorite_music],['Favorite entertainment',selectedProfile.favorite_entertainment],['Favorite food',selectedProfile.favorite_food],['Something I’m good at',selectedProfile.skill],['Talk to me about',selectedProfile.talk_to_me_about],['Random fact',selectedProfile.random_fact],['This year I want to',selectedProfile.year_goal]];$('viewFacts').innerHTML=facts.filter(x=>x[1]).map(x=>`<div class="fact"><small>${esc(x[0])}</small><strong>${esc(x[1])}</strong></div>`).join('')||'<div class="empty">This profile is still pretty empty.</div>';$('viewModal').classList.add('open');document.body.classList.add('modal-open')}
function closeView(){$('viewModal').classList.remove('open');document.body.classList.remove('modal-open')}
function startEdit(){closeView();editMode=true;$('formEyebrow').textContent='EDIT PROFILE';$('formTitle').textContent=`Edit ${selectedProfile.first_name}'s profile`;$('saveBtn').textContent='Save changes';$('first_name').value=selectedProfile.first_name||'';$('last_initial').value=selectedProfile.last_initial||'';$('favorite_music').value=selectedProfile.favorite_music||'';$('favorite_entertainment').value=selectedProfile.favorite_entertainment||'';$('favorite_food').value=selectedProfile.favorite_food||'';$('interests').value=(selectedProfile.interests||[]).join(', ');$('skill').value=selectedProfile.skill||'';$('career_goal').value=selectedProfile.career_goal||'';$('talk_to_me_about').value=selectedProfile.talk_to_me_about||'';$('random_fact').value=selectedProfile.random_fact||'';$('year_goal').value=selectedProfile.year_goal||'';$('pin').value='';$('formMessage').innerHTML='';$('formModal').classList.add('open');document.body.classList.add('modal-open')}
window.addEventListener('keydown',e=>{if(e.key==='Escape'){closeForm();closeView()}})
init();